/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./components/PlatformExpress.js";
export * from "./interfaces/interfaces.js";
export * from "./interfaces/PlatformExpressSettings.js";
export * from "./interfaces/PlatformExpressStaticsOptions.js";
export * from "./middlewares/staticsMiddleware.js";
export * from "./services/PlatformExpressHandler.js";
