approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableImmutableInstalls: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 2w
npmPreapprovedPackages:
  - "@tsed/monorepo-utils@3.3.3"

yarnPath: .yarn/releases/yarn-4.18.0.cjs
