version: "3.3"
services:
  test:
    image: tsed/root
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ./packages:/src/packages
    ports:
      - "8081:8081"
