/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./decorators/useCache.js";
export * from "./interceptors/PlatformCacheInterceptor.js";
export * from "./interfaces/interfaces.js";
export * from "./interfaces/PlatformCachedObject.js";
export * from "./interfaces/PlatformCacheOptions.js";
export * from "./services/PlatformCache.js";
export * from "./utils/getPrefix.js";
export * from "./utils/isEndpoint.js";
