/**
 * @file Automatically generated by barrelsby.
 */

export * from "./decorators/useCache";
export * from "./interceptors/PlatformCacheInterceptor";
export * from "./interfaces/PlatformCacheOptions";
export * from "./interfaces/PlatformCachedObject";
export * from "./interfaces/interfaces";
export * from "./services/PlatformCache";
export * from "./utils/getInterceptorOptions";
export * from "./utils/getPrefix";
export * from "./utils/isEndpoint";
