import {Type} from "@tsed/core";
import {IProvider, ProviderScope} from "../interfaces";
import {registerProvider} from "../registries/ProviderRegistry";

/**
 * The decorators `@Injectable()` declare a new service can be injected in other service, controller, interceptor, etc.. on there `constructor`.
 * All classes annotated with `@Injectable()` are built one time, excepted if you change the default provider configuration.
 *
 * <<< @/docs/docs/snippets/providers/getting-started-injectable.ts
 *
 * ::: tip
 * `@Injectable()` use the `reflect-metadata` to collect and inject the built provided to other services.
 * :::
 *
 * ### Options
 *
 * - type (@@ProviderType@@  or `string`): Kind of provider. (Default: `ProviderType.PROVIDER`)
 * - scope (@@ProviderScope@): Kind of provider. (Default: `ProviderScope.SINGLETON`)
 * - deps (`Type<any>`): List of class or provider which will be injected to the constructor (Note: This options override default metadata generated by Typescript).
 *
 * @returns {Function}
 * @decorator
 */
export function Injectable(options: Partial<IProvider<any>> = {scope: ProviderScope.SINGLETON}): Function {
  return (provide: Type<any>) => {
    registerProvider({
      ...options,
      provide
    });
  };
}
