/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./builder/PlatformServerlessHttp.js";
export * from "./decorators/serverlessContext.js";
export * from "./decorators/serverlessEvent.js";
