import "../src/index.js";

import * as sharedFiltersTest from "./shared/filters.js";
import * as sharedHelpersTest from "./shared/helpers.js";
import * as sharedIncludesTest from "./shared/includes.js";
import * as sharedTest from "./shared/index.js";
import * as sharedPartialsTest from "./shared/partials.js";

describe("integration", () => {
  sharedTest.test("pug");
  sharedTest.test("ejs");
  sharedTest.test("swig");
  sharedTest.test("jazz");
  sharedTest.test("jqtpl");
  sharedTest.test("liquor");
  sharedTest.test("haml");
  sharedTest.test("hamlet");
  // sharedTest.test("haml-coffee");
  sharedTest.test("hogan");
  sharedPartialsTest.test("hogan");
  sharedTest.test("dust");
  sharedPartialsTest.test("dust");
  // const dustTest = await import("./shared/dust");
  // dustTest.test("dust");

  sharedTest.test("handlebars");
  sharedPartialsTest.test("handlebars");
  sharedHelpersTest.test("handlebars");
  // sharedTest.test("underscore");
  // sharedPartialsTest.test("underscore");
  sharedTest.test("lodash");
  sharedTest.test("walrus");
  sharedTest.test("mustache");
  sharedPartialsTest.test("mustache");
  sharedTest.test("just");
  sharedTest.test("ect");
  sharedTest.test("mote");
  sharedTest.test("atpl");
  sharedTest.test("plates");
  sharedTest.test("templayed");
  sharedTest.test("twig");
  sharedTest.test("dot");
  sharedTest.test("ractive");
  sharedPartialsTest.test("ractive");
  sharedTest.test("nunjucks");
  sharedFiltersTest.test("nunjucks");
  sharedIncludesTest.test("nunjucks");
  sharedTest.test("htmling");
  sharedTest.test("vash");
  sharedHelpersTest.test("vash");
  sharedTest.test("slm");
  // sharedTest.test("bracket");
  sharedTest.test("velocityjs");
  sharedTest.test("squirrelly");
  sharedPartialsTest.test("squirrelly");
  sharedHelpersTest.test("squirrelly");
  sharedTest.test("twing");

  //require("./shared/react").test("react");
});
