export const DI_INVOKE_OPTIONS = Symbol("DI_INVOKE_OPTIONS");
export const DI_INJECTABLE_PROPS = Symbol("DI_INJECTABLE_PROPS");
export const DI_USE_OPTIONS = "DI_USE_OPTIONS";
export const DI_USE_PARAM_OPTIONS = "DI_USE_PARAM_OPTIONS";
export const DI_INTERCEPTOR_OPTIONS = "DI_INTERCEPTOR_OPTIONS";
