export enum ParamTypes {
  NEXT_FN = "NEXT_FN",
  ERR = "ERR",
  REQUEST = "REQUEST",
  RESPONSE = "RESPONSE",
  RESPONSE_DATA = "RESPONSE_DATA",
  ENDPOINT_INFO = "ENDPOINT_INFO",
  CONTEXT = "CONTEXT",
  BODY = "BODY",
  PATH = "PATH",
  QUERY = "QUERY",
  HEADER = "HEADER",
  COOKIES = "COOKIES",
  LOCALS = "LOCALS",
  SESSION = "SESSION",
  FORM_DATA = "FORM_DATA"
}
