/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./decorators/onAny.js";
export * from "./decorators/onEvent.js";
export * from "./EventEmitterModule.js";
export * from "./interfaces/EventEmitterStore.js";
export * from "./interfaces/interfaces.js";
export * from "./services/EventEmitterFactory.js";
