/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./components/PlatformFastify.js";
export * from "./interfaces/interfaces.js";
export * from "./interfaces/PlatformFastifySettings.js";
export * from "./services/PlatformFastifyRequest.js";
export * from "./services/PlatformFastifyResponse.js";
